export enum UserRole {
  ADMIN = "ADMIN",
  USER = "USER",
  FREELANCER = "FREELANCER",
  TEAM_LEAD = "TEAM_LEAD",
  ORGANIZATION_ADMIN = "ORGANIZATION_ADMIN",
  ENTITY_ADMIN = "ENTITY_ADMIN",
}

export enum BillingModel {
  PAY_AS_YOU_GO = "PAY_AS_YOU_GO",
  PREPAID_CREDITS = "PREPAID_CREDITS",
  SEAT_BASED = "SEAT_BASED",
}

export enum ProjectStatus {
  DRAFT = "DRAFT",
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum ContractStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum EventType {
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_ASSIGNED = "PROJECT_ASSIGNED",
  PROJECT_COMPLETED = "PROJECT_COMPLETED",
  FREELANCER_HIRED = "FREELANCER_HIRED",
  PAYMENT_PROCESSED = "PAYMENT_PROCESSED",
  CREDIT_PURCHASED = "CREDIT_PURCHASED",
  SUBSCRIPTION_RENEWED = "SUBSCRIPTION_RENEWED",
}
