version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: billforge-postgres
    environment:
      POSTGRES_USER: billforge
      POSTGRES_PASSWORD: billforge_password
      POSTGRES_DB: billforge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U billforge"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: billforge-backend
    environment:
      - DATABASE_URL=postgresql://billforge:billforge_password@postgres:5432/billforge?schema=public
      - PORT=3001
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
    driver: local

