services:
  postgres:
    image: postgres:15-alpine
    container_name: fmb-postgres
    environment:
      POSTGRES_USER: fmb_user
      POSTGRES_PASSWORD: fmb_password
      POSTGRES_DB: freelancer_marketplace_billing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fmb_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: fmb-backend
    environment:
      - DATABASE_URL=postgresql://fmb_user:fmb_password@postgres:5432/freelancer_marketplace_billing?schema=public
      - PORT=3001
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: fmb-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
    driver: local

